src/component/DeltakerPanel.module.scss
src/component/DeltakerPanel.tsx
src/globals.module.scss
src/page/gjennomforing-detaljer/GjennomforingDetaljerPage.tsx

Noen få av justeringene fra https://trello.com/c/beKBPPsD/337-sm%C3%A5fiks-visuelt-tiltaksansvarlig

Fikser på styling

---

src/component/GjennomforingGenerellInfo.tsx
src/page/gjennomforing-detaljer/GjennomforingDetaljerPage.tsx
src/page/gjennomforing-detaljer/tilgangskontroll/Tilgangskontroll.tsx

https://trello.com/c/beKBPPsD/337-sm%C3%A5fiks-visuelt-tiltaksansvarlig

Småfix på styling

---

src/page/gjennomforing-detaljer/endringsmeldinger/Endringsmeldinger.tsx
src/page/gjennomforing-detaljer/heading/Heading.module.scss
src/page/gjennomforing-detaljer/heading/Heading.tsx
src/page/legg-til-gjennomforing-tilgang/gjennomforing-panel/GjennomforingPanel.tsx

https://trello.com/c/UIQ1bq4K/422-sm%C3%A5fiks

Små justeringer på header inne på gjennomføring

---

src/page/gjennomforing-detaljer/endringsmeldinger/endringsmelding/innhold/AvsluttingInnhold.tsx
src/page/gjennomforing-detaljer/endringsmeldinger/endringsmelding/innhold/EndringsmeldingInnhold.tsx
src/page/gjennomforing-detaljer/endringsmeldinger/endringsmelding/innhold/OppstartInnhold.tsx

Co-authored-by: Alexander Gård <alexander.gard@nav.no>

Retter navn på statusårsaker

---

src/api/schema/schema.ts
src/mock/data.ts
src/mock/handlers/mock-handlers.ts
src/page/forside/gjennomforing-liste/gjennomforing-panel/GjennomforingPanel.module.scss
src/page/forside/gjennomforing-liste/gjennomforing-panel/GjennomforingPanel.tsx

https://github.com/navikt/amt-tiltak/pull/327

Viser merkelapp på gjennomføringer når det er skjermede deltakere

---

src/page/gjennomforing-detaljer/endringsmeldinger/endringsmeldingsliste/EndringsmeldingListe.tsx

https://trello.com/c/ZhIAfHzW/910-tekstendring-i-tiltaksadministrasjon

endrer tekst

---

.github/workflows/cypress-cache.yaml
.github/workflows/cypress.yaml
.github/workflows/deploy.yaml
.github/workflows/gh-pages.yaml
.github/workflows/lint-and-test.yaml
.github/workflows/pr-deploy.yaml
README.md
pnpm-lock.yaml

https://trello.com/c/8LUAUqsH/984-oppdatere-designsystemet-til-v-400

Bump versjon av pnpm

---

package.json
pnpm-lock.yaml
src/component/header/Header.tsx
src/index.scss

https://trello.com/c/8LUAUqsH/984-oppdatere-designsystemet-til-v-400

Bump designsystemet

---

package.json
pnpm-lock.yaml

https://trello.com/c/NMoTu8HC/1078-oppdater-til-versjon-5-av-designsystemet

Bump designsystemet til versjon 5

---

.github/dependabot.yml

https://trello.com/c/98AWvxFu/1086-sette-opp-dependabot-for-frontendflater

Legge til dependabot.yaml

---

.github/workflows/pr-cleanup.yaml
.github/workflows/pr-comment-link.yaml
.github/workflows/pr-deploy.yaml

Reverts navikt/amt-tiltaksansvarlig-flate#191

Revert "Ikke deploy automatisk om PR kommer fra fork"

---

src/page/gjennomforing-detaljer/MeldingerFraArrangor.tsx
src/page/gjennomforing-detaljer/endringsmeldinger/Endringsmeldinger.module.scss

https://trello.com/c/DeB4cyr2/1110-kurs-telling-av-vurderinger

legge til antall vurderinger i tab

---

src/component/spa-lenkepanel/SpaLenkepanel.tsx
src/hooks/useLocalStorage.ts
src/page/forside/gjennomforing-liste/GjennomforingListe.module.scss
src/page/forside/gjennomforing-liste/GjennomforingListe.tsx
src/page/forside/gjennomforing-liste/gjennomforing-panel/GjennomforingPanel.module.scss
src/page/forside/gjennomforing-liste/gjennomforing-panel/GjennomforingPanel.tsx

https://trello.com/c/rs5xITfN/1026-sm%C3%A5fiks-nav-tiltaksadministrasjon

Legge scrollPossition i sessonStorage

---

src/page/gjennomforing-detaljer/vurderinger/VurderingerListe.tsx

https://trello.com/c/DoHjalBb/1130-tekst-kurs-navflaten

endrer infotekst for vurderinger for kurs

---

public/mockServiceWorker.js
src/api/schema/schema.ts
src/mock/data.ts

https://trello.com/c/5971OHtX/1204-legge-til-ny-endre-status-p%C3%A5-gjennomf%C3%B8ringer

legger til ny deltakerlistestatus PLANLAGT

---

src/api/schema/schema.ts

https://trello.com/c/5971OHtX/1204-legge-til-ny-endre-status-p%C3%A5-gjennomf%C3%B8ringer

fjerner APENT_FOR_INNSOK

---

src/page/forside/Forside.module.scss
src/page/forside/Forside.tsx

https://trello.com/c/1wM8GIDT/1716-aft-leveranse-innf%C3%B8ring-i-endringsmeldingsappen-for-tiltaksansvarlige

Alert ta ansvarlig om nye endringer

---

src/page/forside/Forside.module.scss
src/page/forside/Forside.tsx

https://trello.com/c/ZljsmPze/1944-etter-lansering-oppdater-info-meldinger

Lager ny infotekst som skal vises etter neste lansering

---

src/page/forside/Forside.tsx

https://trello.com/c/2I38WBNv/2004-oppdatere-innf%C3%B8ringstekster

ny innføringstekst

---

src/page/forside/Forside.module.scss
src/page/forside/Forside.tsx

https://trello.com/c/8MBvUnyf/2028-fjerne-alertstriper

Fjerne innføringstekst

---

src/component/header/Header.tsx

https://nav-it.slack.com/archives/C04D6KP2A48/p1737106050642129

Endre url for tiltaksgjennomforinger til gjennomforinger

---

src/api/api.ts
src/hooks/useDeferredFetch.ts
src/hooks/useFetch.ts
src/page/gjennomforing-detaljer/GjennomforingDetaljerPage.tsx

https://trello.com/c/akRlU4wC/2114-sette-opp-kobling-mellom-endringsmeldinger-siden-og-deltakerlisten

Sørger for redirect av brukere som går til gjennomføring de ikke har tilgang til

---

src/page/gjennomforing-detaljer/vurderinger/NyFlateInfoStripe.tsx

https://trello.com/c/akRlU4wC/2114-sette-opp-kobling-mellom-endringsmeldinger-siden-og-deltakerlisten

url skal føre til deltakerliste fane

---

src/component/system-info-message/SystemInfoMessage.tsx

https://trello.com/c/HmUuIjye/2287-innf%C3%B8ringstekster

Endre info tekst om kurs lanseringsdato

---

src/component/system-info-message/SystemInfoMessage.module.scss
src/component/system-info-message/SystemInfoMessage.tsx

https://trello.com/c/jENV0YQz/2304-oppdatere-tekst-i-infomelding-2

Endrer infomelding
